### ISSUE TITLE
真心感谢作者

### ISSUE THREAD

**Issue by oumaizi** [wange1228/DoubanX_crx#1]
因为一直比较喜欢看书的缘故，就比较喜欢逛一些网络书城，京东，亚马逊这些。看到一本书感觉封面挺好，标题也不错，就会想大概怎么样，这时候就想通过豆瓣去了解，发现每次都要重复，复制书名-粘贴到搜索栏-搜索页-点开页面-看到评分，真的是十分的繁琐，今天刚好想去找找有没有能直接在页面上显示豆瓣评分的，没想到在这真找到了，真的谢谢作者啦。

**Comment by wange1228** [comment]
@oumaizi 感谢支持呀，你的需求也是我的痛点，所以就做了这个插件。如果对这个插件有任何建议和想法都可以提给我，帮我一起完善这个插件的功能 :-)
