### ISSUE TITLE
反馈：图书信息抓取有误

### ISSUE THREAD

**Issue by fzhw88** [wange1228/DoubanX_crx#4]
非常感谢作者的开发，反馈一个错误。

亚马逊页面：https://www.amazon.cn/dp/B00HHK8LZ2
东野圭吾的《秘密》，抓取到的评分却是：https://book.douban.com/subject/5918443/，不相关的图书。

基于有可能发生错误这个现实，希望作者考虑在小窗上添加显示图书标题，作者，出版社等基本信息，便于使用者来判断是否有误，橡这个如果不是看到分数太低不现实，我不会怀疑它抓取错了数据~

**Comment by fzhw88** [comment]
亚马逊：https://www.amazon.cn/dp/B00OJW77GA/
抓到的豆瓣：https://book.douban.com/subject/1235410/
正确的豆瓣：https://book.douban.com/subject/26164486/

看起来这个插件并非按照书号在抓数据，这样错误的几率蛮大。

**Comment by wange1228** [comment]
@fzhw88 感谢反馈，目前是用书名去查询数据，误差的问题确实存在，你的建议很好，近期我会修复更新

**Comment by wange1228** [comment]
@fzhw88 扩展已经更新到2.0版本，改成通过ISBN查询数据，查询不到再用书名去查，结果精确很多，欢迎使用

**Comment by fzhw88** [comment]
@wange1228 感谢感谢，我自己提了建议之后忘了，让后自己写了个油猴子脚本用着，刚刚才看到你更新了，抱歉~回头试试~
